export const GET_ME_SONGS_REQUEST = 'GET_ME_SONGS_REQUEST';
export const GET_ME_SONGS_ERROR = 'GET_ME_SONGS_ERROR';
export const GET_ME_SONGS_SUCCESS = 'GET_ME_SONGS_SUCCESS';

export const GET_LIKED_SONGS_REQUEST = 'GET_LIKED_SONGS_REQUEST';
export const GET_LIKED_SONGS_ERROR = 'GET_LIKED_SONGS_ERROR';
export const GET_LIKED_SONGS_SUCCESS = 'GET_LIKED_SONGS_SUCCESS';
