export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCES = 'USER_INFO_SUCCES';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const UPLOAD_TRACK = 'UPLOAD_TRACK';
