export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_ERROR = 'CREATE_PLAYLIST_ERROR';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';

export const UPDATE_PLAYLIST_REQUEST = 'UPDATE_PLAYLIST_REQUEST';
export const UPDATE_PLAYLIST_ERROR = 'UPDATE_PLAYLIST_ERROR';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';

export const ADD_LIKE_TO_SONG = 'ADD_LIKE_TO_SONG'

export const GET_PLAYLIST_REQUEST = 'GET_PLAYLIST_REQUEST';
export const GET_PLAYLIST_ERROR = 'GET_PLAYLIST_ERROR';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';

export const GET_PLAYLISTS_REQUEST = 'GET_PLAYLISTS_REQUEST';
export const GET_PLAYLISTS_ERROR = 'GET_PLAYLISTS_ERROR';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';

export const DELETE_PLAYLIST_REQUEST = 'DELETE_PLAYLIST_REQUEST';
export const DELETE_PLAYLIST_ERROR = 'DELETE_PLAYLIST_ERROR';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
