export const GET_SONGS_REQUEST = 'GET_SONGS_REQUEST';
export const GET_SONGS_ERROR = 'GET_SONGS_ERROR';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONG_REQUEST = 'GET_SONG_REQUEST';
export const GET_SONG_ERROR = 'GET_SONG_ERROR';
export const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
export const ADD_LIKE_TO_SONG = '.ADD_LIKE_TO_SONG';
export const SONG_UPDATING = 'SONG_UPDATING';
export const SONG_UPDATING_ERROR = 'SONG_UPDATING_ERROR';

export const SONG_DELETE_REQUEST = 'SONG_DELETING';
export const SONG_DELETE_ERROR = 'SONG_DELETING_ERROR';
export const SONG_DELETE_SUCCESS = 'SONG_DELETED_SUCCESS';

export const EDIT_SONG = 'EDIT_SONG';
export const OPEN_INFO_MODAL = 'OPEN_INFO_MODAL';
export const CLOSE_INFO_MODAL = 'CLOSE_INFO_MODAL';
