export const SONGS_REQUEST = 'SONGS_REQUEST';
export const SONGS_SUCCES = 'SONGS_SUCCES';
export const SONGS_ERROR = 'SONGS_ERROR';

export const SONGS_BY_PARAM_REQUEST = 'SONGS_BY_PARAM_REQUEST';
export const SONGS_BY_PARAM_SUCCES = 'SONGS_BY_PARAM_SUCCES';
export const SONGS_BY_PARAM_ERROR = 'SONGS_BY_PARAM_ERROR';
