export const GET_SONGS_REQUEST = 'GET_SONGS_REQUEST';
export const GET_SONGS_ERROR = 'GET_SONGS_ERROR';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';

export const GET_SONG_REQUEST = 'GET_SONG_REQUEST';
export const GET_SONG_ERROR = 'GET_SONG_ERROR';
export const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
export const ADD_LIKE_TO_SONG = 'ADD_LIKE_TO_SONG';

export const SONG_DELETE_REQUEST = 'SONG_DELETING';
export const SONG_DELETE_ERROR = 'SONG_DELETING_ERROR';
export const SONG_DELETE_SUCCESS = 'SONG_DELETED_SUCCESS';

export const SONG_EDIT_REQUEST = 'SONG_EDIT_REQUEST';
export const SONG_EDIT_ERROR = 'SONG_EDIT_ERROR';
export const EDIT_SONG_SUCCESS = 'EDIT_SONG';
